services:
  - type: web
    name: travel-planner-backend
    env: java
    buildCommand: cd backend/WarderGen && mvn clean install -DskipTests
    startCommand: cd backend/WarderGen && java -Dspring.profiles.active=production -Dserver.port=$PORT -Dserver.address=0.0.0.0 -jar target/*.jar
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "https://travel-planner-frontend-one.vercel.app,https://your-frontend-app.vercel.app,http://localhost:3000,http://localhost:5173"
      - key: DATABASE_URL
        sync: false # You'll set this manually to your Neon connection string
