/**
 * Export utilities for itineraries and trip data
 */

/**
 * Format itinerary for printing/PDF
 */
export const formatItineraryForPrint = (itinerary, trip) => {
  if (!itinerary) return '';

  const days = itinerary.days || itinerary.itinerary || [];
  const title = itinerary.title || `Trip to ${trip?.destination || 'Unknown'}`;
  const description = itinerary.description || itinerary.trip_summary || '';

  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: 'Inter', -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #1a1a1a; }
        h1 { font-size: 28px; margin-bottom: 8px; }
        h2 { font-size: 20px; margin-top: 24px; margin-bottom: 8px; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; }
        h3 { font-size: 16px; margin-top: 16px; margin-bottom: 4px; }
        p { line-height: 1.6; color: #4a5568; }
        .header { margin-bottom: 32px; }
        .day-card { page-break-inside: avoid; margin-bottom: 24px; padding: 16px; background: #f7fafc; border-radius: 8px; border: 1px solid #e2e8f0; }
        .day-header { font-size: 18px; font-weight: bold; color: #2d3748; margin-bottom: 12px; }
        .activity { margin-bottom: 12px; padding-left: 12px; border-left: 3px solid #48bb78; }
        .activity-time { font-weight: 600; color: #2b6cb0; font-size: 14px; }
        .activity-title { font-weight: 600; color: #1a202c; }
        .activity-desc { color: #4a5568; font-size: 14px; }
        .meta { font-size: 12px; color: #718096; margin-top: 4px; }
        .budget { background: #f0fff4; border: 1px solid #c6f6d5; border-radius: 8px; padding: 12px; margin-bottom: 24px; }
        .tips { background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 12px; margin-bottom: 24px; }
        @media print { body { padding: 0; } .no-print { display: none; } }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #a0aec0; text-align: center; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${title}</h1>
        ${description ? `<p>${description}</p>` : ''}
        ${trip?.destination ? `<p>📍 <strong>Destination:</strong> ${trip.destination}</p>` : ''}
        ${trip?.startDate ? `<p>📅 <strong>Dates:</strong> ${new Date(trip.startDate).toLocaleDateString()} — ${new Date(trip.endDate).toLocaleDateString()}</p>` : ''}
        ${trip?.budget ? `<p>💰 <strong>Budget:</strong> $${trip.budget}</p>` : ''}
      </div>
  `;

  // Budget breakdown
  if (itinerary.budgetBreakdown || itinerary.overall_budget_breakdown) {
    const budget = itinerary.budgetBreakdown || itinerary.overall_budget_breakdown;
    html += `<div class="budget"><h3>💰 Budget Breakdown</h3>`;
    if (budget.accommodation_estimate) html += `<p><strong>Accommodation:</strong> ${budget.accommodation_estimate}</p>`;
    if (budget.food_estimate) html += `<p><strong>Food:</strong> ${budget.food_estimate}</p>`;
    if (budget.activities_estimate) html += `<p><strong>Activities:</strong> ${budget.activities_estimate}</p>`;
    if (budget.transport_estimate) html += `<p><strong>Transport:</strong> ${budget.transport_estimate}</p>`;
    html += `</div>`;
  }

  // Days
  days.forEach((day, index) => {
    const activities = day.activities || [];
    html += `
      <div class="day-card">
        <div class="day-header">Day ${index + 1}${day.title ? ': ' + day.title : ''}</div>
        ${day.overview ? `<p>${day.overview}</p>` : ''}
        ${activities.map(act => `
          <div class="activity">
            ${act.time ? `<div class="activity-time">${act.time}${act.duration ? ' · ' + act.duration : ''}</div>` : ''}
            <div class="activity-title">${act.title || 'Activity'}</div>
            ${act.description ? `<div class="activity-desc">${act.description}</div>` : ''}
            ${act.location ? `<div class="meta">📍 ${act.location}</div>` : ''}
            ${act.estimated_cost ? `<div class="meta">💰 ${act.estimated_cost}</div>` : ''}
          </div>
        `).join('')}
      </div>
    `;
  });

  // Tips
  const tips = itinerary.essentialTips || itinerary.essential_travel_tips || itinerary.tips || [];
  if (tips.length > 0) {
    html += `<div class="tips"><h3>💡 Essential Tips</h3><ul>${tips.map(t => `<li>${t}</li>`).join('')}</ul></div>`;
  }

  html += `
      <div class="footer">
        <p>Generated by WanderGen — AI-Powered Travel Planning</p>
        <p>${new Date().toLocaleDateString()}</p>
      </div>
    </body>
    </html>
  `;

  return html;
};

/**
 * Open print dialog for itinerary
 */
export const printItinerary = (itinerary, trip) => {
  const html = formatItineraryForPrint(itinerary, trip);
  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
};

/**
 * Download itinerary as HTML file (for PDF conversion)
 */
export const downloadItineraryHTML = (itinerary, trip) => {
  const html = formatItineraryForPrint(itinerary, trip);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `itinerary-${trip?.destination?.toLowerCase().replace(/\s+/g, '-') || 'travel'}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Copy itinerary as formatted text to clipboard
 */
export const copyItineraryToClipboard = async (itinerary, trip) => {
  const days = itinerary.days || itinerary.itinerary || [];
  let text = `🗺️ ${itinerary.title || `Trip to ${trip?.destination || 'Unknown'}`}\n`;
  text += `${'='.repeat(40)}\n\n`;

  days.forEach((day, index) => {
    text += `📅 Day ${index + 1}${day.title ? ': ' + day.title : ''}\n`;
    text += `${'-'.repeat(30)}\n`;
    if (day.overview) text += `${day.overview}\n\n`;
    (day.activities || []).forEach(act => {
      if (act.time) text += `  ⏰ ${act.time}${act.duration ? ` (${act.duration})` : ''}\n`;
      text += `  📌 ${act.title || 'Activity'}\n`;
      if (act.description) text += `     ${act.description}\n`;
      if (act.location) text += `     📍 ${act.location}\n`;
      if (act.estimated_cost) text += `     💰 ${act.estimated_cost}\n`;
      text += '\n';
    });
  });

  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
};

/**
 * Generate Google Calendar URL for trip
 */
export const generateCalendarUrl = (trip) => {
  if (!trip?.startDate || !trip?.endDate) return null;

  const start = new Date(trip.startDate).toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  const end = new Date(trip.endDate).toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: `Trip to ${trip.destination || 'Unknown'}`,
    dates: `${start}/${end}`,
    details: `Travel itinerary for ${trip.destination || 'Unknown'}\n\nGenerated by WanderGen`,
    sf: 'true',
    output: 'xml',
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
};

/**
 * Generate share text for social media
 */
export const getShareText = (trip) => {
  const itineraryUrl = trip?.shareUrl || window.location.href;
  return `🗺️ Planning an amazing trip to ${trip?.destination || 'Unknown'} with WanderGen!\n\n${itineraryUrl}`;
};
